// Code generated by wlgen. DO NOT EDIT.
// Vendored from deedles.dev/wl/examples/internal/layershell/client/protocol.go
// with GetPopup method removed (depends on xdg internals not needed here).

package layershell

import (
	wl "deedles.dev/wl/client"
	"deedles.dev/wl/wire"
	"fmt"
)

const (
	LayerShellV1Interface = "zwlr_layer_shell_v1"
	LayerShellV1Version   = 5
)

type LayerShellV1 struct {
	OnDelete func()

	state wire.State
	id    uint32
}

func NewLayerShellV1(state wire.State) *LayerShellV1 {
	return &LayerShellV1{state: state}
}

func BindLayerShellV1(state wire.State, registry wire.Binder, name, version uint32) *LayerShellV1 {
	obj := NewLayerShellV1(state)
	state.Add(obj)
	registry.Bind(name, wire.NewID{Interface: LayerShellV1Interface, Version: version, ID: obj.ID()})
	return obj
}

func (obj *LayerShellV1) State() wire.State {
	return obj.state
}

func (obj *LayerShellV1) Dispatch(msg *wire.MessageBuffer) error {
	return wire.UnknownOpError{
		Interface: "zwlr_layer_shell_v1",
		Type:      "event",
		Op:        msg.Op(),
	}
}

func (obj *LayerShellV1) ID() uint32 {
	return obj.id
}

func (obj *LayerShellV1) SetID(id uint32) {
	obj.id = id
}

func (obj *LayerShellV1) Delete() {
	if obj.OnDelete != nil {
		obj.OnDelete()
	}
}

func (obj *LayerShellV1) String() string {
	return fmt.Sprintf("%v(%v)", "zwlr_layer_shell_v1", obj.id)
}

func (obj *LayerShellV1) MethodName(op uint16) string {
	switch op {
	}

	return "unknown method"
}

func (obj *LayerShellV1) Interface() string {
	return LayerShellV1Interface
}

func (obj *LayerShellV1) Version() uint32 {
	return LayerShellV1Version
}

func (obj *LayerShellV1) GetLayerSurface(surface *wl.Surface, output *wl.Output, layer LayerShellV1Layer, namespace string) (id *LayerSurfaceV1) {
	builder := wire.NewMessage(obj, 0)

	id = NewLayerSurfaceV1(obj.state)
	obj.state.Add(id)
	builder.WriteObject(id)
	builder.WriteObject(surface)
	builder.WriteObject(output)
	builder.WriteUint(uint32(layer))
	builder.WriteString(namespace)

	builder.Method = "get_layer_surface"
	builder.Args = []any{id, surface, output, layer, namespace}
	obj.state.Enqueue(builder)
	return id
}

func (obj *LayerShellV1) Destroy() {
	builder := wire.NewMessage(obj, 1)

	builder.Method = "destroy"
	builder.Args = []any{}
	obj.state.Enqueue(builder)
	return
}

type LayerShellV1Error int64

const (
	LayerShellV1ErrorRole               LayerShellV1Error = 0
	LayerShellV1ErrorInvalidLayer       LayerShellV1Error = 1
	LayerShellV1ErrorAlreadyConstructed LayerShellV1Error = 2
)

func (enum LayerShellV1Error) String() string {
	switch enum {
	case 0:
		return "LayerShellV1ErrorRole"
	case 1:
		return "LayerShellV1ErrorInvalidLayer"
	case 2:
		return "LayerShellV1ErrorAlreadyConstructed"
	}
	return "<invalid LayerShellV1Error>"
}

type LayerShellV1Layer int64

const (
	LayerShellV1LayerBackground LayerShellV1Layer = 0
	LayerShellV1LayerBottom     LayerShellV1Layer = 1
	LayerShellV1LayerTop        LayerShellV1Layer = 2
	LayerShellV1LayerOverlay    LayerShellV1Layer = 3
)

func (enum LayerShellV1Layer) String() string {
	switch enum {
	case 0:
		return "LayerShellV1LayerBackground"
	case 1:
		return "LayerShellV1LayerBottom"
	case 2:
		return "LayerShellV1LayerTop"
	case 3:
		return "LayerShellV1LayerOverlay"
	}
	return "<invalid LayerShellV1Layer>"
}

const (
	LayerSurfaceV1Interface = "zwlr_layer_surface_v1"
	LayerSurfaceV1Version   = 5
)

type LayerSurfaceV1Listener interface {
	Configure(serial uint32, width uint32, height uint32)
	Closed()
}

type LayerSurfaceV1 struct {
	Listener LayerSurfaceV1Listener
	OnDelete func()

	state wire.State
	id    uint32
}

func NewLayerSurfaceV1(state wire.State) *LayerSurfaceV1 {
	return &LayerSurfaceV1{state: state}
}

func (obj *LayerSurfaceV1) State() wire.State {
	return obj.state
}

func (obj *LayerSurfaceV1) Dispatch(msg *wire.MessageBuffer) error {
	switch msg.Op() {
	case 0:
		serial := msg.ReadUint()
		width := msg.ReadUint()
		height := msg.ReadUint()

		if err := msg.Err(); err != nil {
			return err
		}

		if obj.Listener == nil {
			return nil
		}
		obj.Listener.Configure(serial, width, height)
		return nil

	case 1:
		if err := msg.Err(); err != nil {
			return err
		}

		if obj.Listener == nil {
			return nil
		}
		obj.Listener.Closed()
		return nil
	}

	return wire.UnknownOpError{
		Interface: "zwlr_layer_surface_v1",
		Type:      "event",
		Op:        msg.Op(),
	}
}

func (obj *LayerSurfaceV1) ID() uint32 {
	return obj.id
}

func (obj *LayerSurfaceV1) SetID(id uint32) {
	obj.id = id
}

func (obj *LayerSurfaceV1) Delete() {
	if obj.OnDelete != nil {
		obj.OnDelete()
	}
}

func (obj *LayerSurfaceV1) String() string {
	return fmt.Sprintf("%v(%v)", "zwlr_layer_surface_v1", obj.id)
}

func (obj *LayerSurfaceV1) MethodName(op uint16) string {
	switch op {
	case 0:
		return "configure"
	case 1:
		return "closed"
	}
	return "unknown method"
}

func (obj *LayerSurfaceV1) Interface() string {
	return LayerSurfaceV1Interface
}

func (obj *LayerSurfaceV1) Version() uint32 {
	return LayerSurfaceV1Version
}

func (obj *LayerSurfaceV1) SetSize(width uint32, height uint32) {
	builder := wire.NewMessage(obj, 0)
	builder.WriteUint(width)
	builder.WriteUint(height)
	builder.Method = "set_size"
	builder.Args = []any{width, height}
	obj.state.Enqueue(builder)
	return
}

func (obj *LayerSurfaceV1) SetAnchor(anchor LayerSurfaceV1Anchor) {
	builder := wire.NewMessage(obj, 1)
	builder.WriteUint(uint32(anchor))
	builder.Method = "set_anchor"
	builder.Args = []any{anchor}
	obj.state.Enqueue(builder)
	return
}

func (obj *LayerSurfaceV1) SetExclusiveZone(zone int32) {
	builder := wire.NewMessage(obj, 2)
	builder.WriteInt(zone)
	builder.Method = "set_exclusive_zone"
	builder.Args = []any{zone}
	obj.state.Enqueue(builder)
	return
}

func (obj *LayerSurfaceV1) SetMargin(top int32, right int32, bottom int32, left int32) {
	builder := wire.NewMessage(obj, 3)
	builder.WriteInt(top)
	builder.WriteInt(right)
	builder.WriteInt(bottom)
	builder.WriteInt(left)
	builder.Method = "set_margin"
	builder.Args = []any{top, right, bottom, left}
	obj.state.Enqueue(builder)
	return
}

func (obj *LayerSurfaceV1) SetKeyboardInteractivity(keyboardInteractivity LayerSurfaceV1KeyboardInteractivity) {
	builder := wire.NewMessage(obj, 4)
	builder.WriteUint(uint32(keyboardInteractivity))
	builder.Method = "set_keyboard_interactivity"
	builder.Args = []any{keyboardInteractivity}
	obj.state.Enqueue(builder)
	return
}

// GetPopup intentionally omitted — depends on xdg internals not needed here.

func (obj *LayerSurfaceV1) AckConfigure(serial uint32) {
	builder := wire.NewMessage(obj, 6)
	builder.WriteUint(serial)
	builder.Method = "ack_configure"
	builder.Args = []any{serial}
	obj.state.Enqueue(builder)
	return
}

func (obj *LayerSurfaceV1) Destroy() {
	builder := wire.NewMessage(obj, 7)
	builder.Method = "destroy"
	builder.Args = []any{}
	obj.state.Enqueue(builder)
	return
}

func (obj *LayerSurfaceV1) SetLayer(layer LayerShellV1Layer) {
	builder := wire.NewMessage(obj, 8)
	builder.WriteUint(uint32(layer))
	builder.Method = "set_layer"
	builder.Args = []any{layer}
	obj.state.Enqueue(builder)
	return
}

func (obj *LayerSurfaceV1) SetExclusiveEdge(edge LayerSurfaceV1Anchor) {
	builder := wire.NewMessage(obj, 9)
	builder.WriteUint(uint32(edge))
	builder.Method = "set_exclusive_edge"
	builder.Args = []any{edge}
	obj.state.Enqueue(builder)
	return
}

type LayerSurfaceV1KeyboardInteractivity int64

const (
	LayerSurfaceV1KeyboardInteractivityNone      LayerSurfaceV1KeyboardInteractivity = 0
	LayerSurfaceV1KeyboardInteractivityExclusive LayerSurfaceV1KeyboardInteractivity = 1
	LayerSurfaceV1KeyboardInteractivityOnDemand  LayerSurfaceV1KeyboardInteractivity = 2
)

func (enum LayerSurfaceV1KeyboardInteractivity) String() string {
	switch enum {
	case 0:
		return "LayerSurfaceV1KeyboardInteractivityNone"
	case 1:
		return "LayerSurfaceV1KeyboardInteractivityExclusive"
	case 2:
		return "LayerSurfaceV1KeyboardInteractivityOnDemand"
	}
	return "<invalid LayerSurfaceV1KeyboardInteractivity>"
}

type LayerSurfaceV1Error int64

const (
	LayerSurfaceV1ErrorInvalidSurfaceState         LayerSurfaceV1Error = 0
	LayerSurfaceV1ErrorInvalidSize                  LayerSurfaceV1Error = 1
	LayerSurfaceV1ErrorInvalidAnchor                LayerSurfaceV1Error = 2
	LayerSurfaceV1ErrorInvalidKeyboardInteractivity LayerSurfaceV1Error = 3
	LayerSurfaceV1ErrorInvalidExclusiveEdge         LayerSurfaceV1Error = 4
)

func (enum LayerSurfaceV1Error) String() string {
	switch enum {
	case 0:
		return "LayerSurfaceV1ErrorInvalidSurfaceState"
	case 1:
		return "LayerSurfaceV1ErrorInvalidSize"
	case 2:
		return "LayerSurfaceV1ErrorInvalidAnchor"
	case 3:
		return "LayerSurfaceV1ErrorInvalidKeyboardInteractivity"
	case 4:
		return "LayerSurfaceV1ErrorInvalidExclusiveEdge"
	}
	return "<invalid LayerSurfaceV1Error>"
}

type LayerSurfaceV1Anchor int64

const (
	LayerSurfaceV1AnchorTop    LayerSurfaceV1Anchor = 1
	LayerSurfaceV1AnchorBottom LayerSurfaceV1Anchor = 2
	LayerSurfaceV1AnchorLeft   LayerSurfaceV1Anchor = 4
	LayerSurfaceV1AnchorRight  LayerSurfaceV1Anchor = 8
)

func (enum LayerSurfaceV1Anchor) String() string {
	switch enum {
	case 1:
		return "LayerSurfaceV1AnchorTop"
	case 2:
		return "LayerSurfaceV1AnchorBottom"
	case 4:
		return "LayerSurfaceV1AnchorLeft"
	case 8:
		return "LayerSurfaceV1AnchorRight"
	}
	return "<invalid LayerSurfaceV1Anchor>"
}
